# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dynamic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dynamic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdynamic.proto\x12\x17\x62ilibili.app.dynamic.v2\"E\n\x0b\x44ynSpaceReq\x12\x10\n\x08host_uid\x18\x01 \x01(\x03\x12\x16\n\x0ehistory_offset\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x05 \x01(\x03\"k\n\x0b\x44ynSpaceRsp\x12\x32\n\x04list\x18\x01 \x03(\x0b\x32$.bilibili.app.dynamic.v2.DynamicItem\x12\x16\n\x0ehistory_offset\x18\x02 \x01(\t\x12\x10\n\x08has_more\x18\x03 \x01(\x08\"\x83\x01\n\x0b\x44ynamicItem\x12\x11\n\tcard_type\x18\x01 \x01(\x05\x12\x30\n\x07modules\x18\x03 \x03(\x0b\x32\x1f.bilibili.app.dynamic.v2.Module\x12/\n\x06\x65xtend\x18\x04 \x01(\x0b\x32\x1f.bilibili.app.dynamic.v2.Extend\"\x86\x01\n\x06Module\x12<\n\rmodule_author\x18\x02 \x01(\x0b\x32%.bilibili.app.dynamic.v2.ModuleAuthor\x12>\n\x0emodule_dynamic\x18\x05 \x01(\x0b\x32&.bilibili.app.dynamic.v2.ModuleDynamic\"A\n\x0cModuleAuthor\x12\x31\n\x06\x61uthor\x18\x03 \x01(\x0b\x32!.bilibili.app.dynamic.v2.UserInfo\"\x18\n\x08UserInfo\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x83\x01\n\rModuleDynamic\x12;\n\x0b\x64yn_archive\x18\x02 \x01(\x0b\x32&.bilibili.app.dynamic.v2.MdlDynArchive\x12\x35\n\x08\x64yn_draw\x18\x07 \x01(\x0b\x32#.bilibili.app.dynamic.v2.MdlDynDraw\"\x1e\n\rMdlDynArchive\x12\r\n\x05\x63over\x18\x02 \x01(\t\"D\n\nMdlDynDraw\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.bilibili.app.dynamic.v2.MdlDynDrawItem\"\x1d\n\x0eMdlDynDrawItem\x12\x0b\n\x03src\x18\x01 \x01(\t\"2\n\x06\x45xtend\x12\x12\n\ndyn_id_str\x18\x01 \x01(\t\x12\x14\n\x0corig_img_url\x18\x05 \x01(\t2a\n\x07\x44ynamic\x12V\n\x08\x44ynSpace\x12$.bilibili.app.dynamic.v2.DynSpaceReq\x1a$.bilibili.app.dynamic.v2.DynSpaceRspb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dynamic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNSPACEREQ']._serialized_start=42
  _globals['_DYNSPACEREQ']._serialized_end=111
  _globals['_DYNSPACERSP']._serialized_start=113
  _globals['_DYNSPACERSP']._serialized_end=220
  _globals['_DYNAMICITEM']._serialized_start=223
  _globals['_DYNAMICITEM']._serialized_end=354
  _globals['_MODULE']._serialized_start=357
  _globals['_MODULE']._serialized_end=491
  _globals['_MODULEAUTHOR']._serialized_start=493
  _globals['_MODULEAUTHOR']._serialized_end=558
  _globals['_USERINFO']._serialized_start=560
  _globals['_USERINFO']._serialized_end=584
  _globals['_MODULEDYNAMIC']._serialized_start=587
  _globals['_MODULEDYNAMIC']._serialized_end=718
  _globals['_MDLDYNARCHIVE']._serialized_start=720
  _globals['_MDLDYNARCHIVE']._serialized_end=750
  _globals['_MDLDYNDRAW']._serialized_start=752
  _globals['_MDLDYNDRAW']._serialized_end=820
  _globals['_MDLDYNDRAWITEM']._serialized_start=822
  _globals['_MDLDYNDRAWITEM']._serialized_end=851
  _globals['_EXTEND']._serialized_start=853
  _globals['_EXTEND']._serialized_end=903
  _globals['_DYNAMIC']._serialized_start=905
  _globals['_DYNAMIC']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
